on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cross build binaries
      - run: make build-prebuilt-binaries