name: release-builds

on:
  push:
    branches: ['feat/build-releases']

jobs:
  build-and-release-binaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create multiarch builds
        run: | 
          make create-release-archive-files
      - uses: ncipollo/release-action@v1
        with:
          tag: v1
          artifacts: ".builds/version-hash.md5, .builds/*.tar.gz, .builds/*.tar.gz.md5"
          allowUpdates: true
          replacesArtifacts: true
