name: release-builds

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build-and-release-binaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check if codebase changed
        id: check-codebase
        run: |
          [ "$(make -s generate-build-hash)" != "$(make -s check-published-build-hash)" ] && echo "changed=true" || echo "changed=false" >> $GITHUB_OUTPUT
      - name: Create multiarch builds
        if: ${{steps.check-codebase.outputs.changed}} == 'true'
        run: | 
          make create-release-archive-files
      - uses: ncipollo/release-action@v1
        if: ${{steps.check-codebase.outputs.changed}} == 'true'
        with:
          tag: v1
          artifacts: ".builds/version-hash.md5, .builds/*.tar.gz, .builds/*.tar.gz.md5"
          allowUpdates: true
          replacesArtifacts: true
